export const MULTIVECTOR_ONTOLOGY_OPCODES = {
  SUM: '∑',
  PRODUCT: '∏',
  INTEGRAL: '∫',
  PARTIAL: '∂',
  NABLA: '∇',
  DELTA: '∆',
  ALPHA: 'α',
  BETA: 'β',
  GAMMA: 'γ',
  DELTA_LOWER: 'δ',
  EPSILON: 'ε',
  ZETA: 'ζ',
  ETA: 'η',
  THETA: 'θ',
  LAMBDA: 'λ',
  MU: 'μ',
  PI: 'π',
  RHO: 'ρ',
  SIGMA: 'σ',
  PHI: 'φ',
  PSI: 'ψ',
  OMEGA: 'ω',
  UNION: '∪',
  INTERSECTION: '∩',
  SUBSET: '⊂',
  SUPERSET: '⊃',
  ELEMENT_OF: '∈',
  NOT_ELEMENT_OF: '∉',
  EMPTY_SET: '∅',
  AND: '∧',
  OR: '∨',
  NOT: '¬',
  FORALL: '∀',
  EXISTS: '∃',
  PLUS_MINUS: '±',
  MULTIPLY: '×',
  DIVIDE: '÷',
  APPROX: '≈',
  NOT_EQUAL: '≠',
  LESS_EQUAL: '≤',
  GREATER_EQUAL: '≥',
  INFINITY: '∞',
  REAL: 'ℝ',
  COMPLEX: 'ℂ',
  RATIONAL: 'ℚ',
  INTEGER: 'ℤ',
  NATURAL: 'ℕ',
  SQRT: '√',
  CBRT: '∛',
  FOURTH_ROOT: '∜',
  DEGREE: '°',
  PRIME: '′',
  DOUBLE_PRIME: '″',
  TENSOR_PRODUCT: '⊗',
  DIRECT_SUM: '⊕',
  CIRCLE_DOT: '⊙'
};

export const OPCODES_ARRAY = Object.values(MULTIVECTOR_ONTOLOGY_OPCODES);

export const OPCODES_BY_CATEGORY = {
  operators: ['∑', '∏', '∫', '∂', '∇', '∆'],
  greek: ['α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'λ', 'μ', 'π', 'ρ', 'σ', 'φ', 'ψ', 'ω'],
  setTheory: ['∪', '∩', '⊂', '⊃', '∈', '∉', '∅'],
  logic: ['∧', '∨', '¬', '∀', '∃'],
  algebra: ['±', '×', '÷', '≈', '≠', '≤', '≥'],
  numberSets: ['ℝ', 'ℂ', 'ℚ', 'ℤ', 'ℕ'],
  tensor: ['⊗', '⊕', '⊙']
};
